# Generated by Django 3.2.18 on 2023-03-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_best_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='best_bidder',
        ),
    ]
