# Generated by Django 3.2.18 on 2023-03-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20230319_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='without_bid',
            field=models.BooleanField(default=True),
        ),
    ]
